export enum userActionTypes {
    USER_CREATION = 'USER_CREATION',
    USER_UPDATE = 'USER_UPDATE',
    GET_USERS = 'GET_USERS',
    GET_USER = 'GET_USER',
    SEARCH_USERS = 'SEARCH_USERS',
    OPTMISTIC_SEARCH_USERS = 'OPTMISTIC_SEARCH_USERS'
}